### ISSUE TITLE
pre_get_posts hook is overriding query

### ISSUE THREAD

**Issue by abdullah1908** [5um17/wp-extended-search#1]
`pre_get_posts` hook is overriding the `wp_query` for other plugins & showing default posts instead of the actual post type list.

Please make [it](https://github.com/5um17/wp-extended-search/blob/master/includes/WP_ES.php#L89) specific so it wouldn't impact for other plugins.

You can try [Simple Job Board](https://wordpress.org/plugins/simple-job-board/) to reproduce the bug.

**Comment by 5um17** [comment]
Hi,

`pre_get_posts` only runs on [search query](https://github.com/5um17/wp-extended-search/blob/master/includes/WP_ES.php#L98).

If it is affecting the search query then `posts_search` filter should be active too?
Anyway could you please provide steps to reproduce the issue?

**Comment by Robbertdk** [comment]
I had the same kind of problem with the Facet WP plugin.

Facet WP creates custom search queries which differs from the main search query this plugin alters. But those FacetWP queries got also altered by this plugin and where resulting incorrect results.

I've added a pull request for this issue: https://github.com/5um17/wp-extended-search/pull/3

In my case I can implement it like this:

```
/**
  * Disable the WP Extended Search on facet filters queries
  *
  * @param Boolean $enabled
  * @param WP_Query $query
  *
  * @return Boolean
  */
function disable_wp_es_on_facet_queries($enabled, $query){
    if ( !empty($query->query['facetwp']) ) {
        return false;
    }
    return $enabled;
}
add_filter('wpes_pre_get_posts_enabled', 'disable_wp_es_on_facet_queries', 10, 2);
```

**Comment by 5um17** [comment]
Hi,

Thanks for reporting the issue!

Even if you disable the `pre_get_posts` still [`posts_search`](https://github.com/5um17/wp-extended-search/blob/master/includes/WP_ES.php#L86) filter will be active. This will alter the results as well. I am not getting why only `pre_get_posts` causing issue?

Also, we have [`wpes_enabled `](https://www.secretsofgeeks.com/2014/09/wordpress-search-tags-and-categories.html#wpes_enabled) filter which can remove both the filters in one go. This is not useful? Is it the secondary query?

Thanks

**Comment by 5um17** [comment]
Reproduced the issue with Simple Job board.
The problem was `$query->is_search` is `true` this is fixed by checking for search string `$query->get( 's' )`.

Another issue was when a real custom search query is fired, there was no way to disable WPES based on query. The filter was working fine but still `posts_search` filter was active so instead of adding two filters I added check for query var `disable_wpes` if this set to `true` WPES's filters are inactive. Here #3 

Example:-
```
add_action('parse_query', function ( $q ){
    $q->set('disable_wpes', true);
});
```

I hope this will work for you.

**Comment by Robbertdk** [comment]
Hi,

Good solution, this will work as well. Thanks!
