### ISSUE TITLE
WordPress 6.0-RC1 causes WordPress database error

### ISSUE THREAD

**Issue by ultrafunk** [5um17/wp-extended-search#12]
Hi,

I'm testing a theme and a few plugins to make sure they work in WordPress 6.0 when it is released, but I keep running into the following error when doing a search with your plugin activated:

**WordPress database error:** [Unknown column 'estt.taxonomy' in 'where clause']
`SELECT SQL_CALC_FOUND_ROWS wp_posts.ID FROM wp_posts WHERE 1=1 AND ( ((wp_posts.post_title LIKE '%testing%') OR (wp_posts.post_content LIKE '%testing%') OR (wp_posts.post_excerpt LIKE '%testing%') OR (estt.taxonomy = 'post_tag' AND est.name LIKE '%testing%'))) AND ((wp_posts.post_type = 'post' AND (wp_posts.post_status = 'publish' OR wp_posts.post_status = 'private')) OR (wp_posts.post_type = 'page' AND (wp_posts.post_status = 'publish' OR wp_posts.post_status = 'private'))) ORDER BY wp_posts.post_title LIKE '%testing%' DESC, wp_posts.post_date DESC LIMIT 0, 12`

The error only appears when searching taxonomies is enabled.

**The test environment is running the following:**

- WordPress 6.0-RC1
- Twenty Twenty-Two Version 1.2 (theme)

**Plugins:**
- WP Extended Search Version 2.1.1
- Wordfence Security Version 7.5.9
- WordPress Beta Tester Version 3.2.1
- Force Login Version 5.6.3

On my production site running WordPress 5.9.3 with the same configuration (minus the WordPress Beta Tester plugin), this error does not occur... Please let me know if you need any more details.

**Comment by 5um17** [comment]
Thanks for the detailed report. I can reproduce the issue and found this is something broken in WordPress so I've reported here https://core.trac.wordpress.org/ticket/55699

You can subscribe to the core ticket and I hope it will be fixed soon.
Thanks again for your contribution!

**Comment by ultrafunk** [comment]
Thank you for looking into this so quickly, and thank you for reporting the bug to the WordPress devs.

I'm a fan of your search plugin, it is simple to use and configure, and it extends the built-in WP-search in just the right ways, so please keep up the good work!

If possible, I would like to donate some funds to you for all your work on the plugin, but I could not find any way to do so...

**Comment by 5um17** [comment]
Hi,

I really appreciate your feedback.
I maintain this plugin as giving back to open source WordPress community. I do not make any living from it and all the work is done in my spare time (You know sometimes it is hard). I can not ask for funds for the support and features of this plugin I just need your contribution as you did now. :)

However, if you just want to buy me a coffee as a token of appreciation, here you go https://www.secretsofgeeks.com/p/donate.html

Again, thank you, you reported this on very time before the release and saved me from flood of requests :D

**Comment by ultrafunk** [comment]
Just installed WordPress 6.0-RC2 and tested your plugin and the bug is now fixed!

Also sent you some PayPal funds that should be enough for (hopefully) two cups of coffee :-)

**Comment by 5um17** [comment]
Glad to know it is fixed.
Of course, it is enough for two cups of coffee 😀 Thank you!
