### ISSUE TITLE
Can't search for tag and author when not logged in

### ISSUE THREAD

**Issue by WenqianC** [5um17/wp-extended-search#18]
Hi,

When searching for keyword in a password protected article, if the person who searches it is not logged in, then the returned result will not contain articles that includes the tag or published by author.
Is this a bug?

Thank you!

**Comment by 5um17** [comment]
Hi,

Password protected posts are not visible in search results. This is default WordPress behavior. You can see this even you disable this plugin.

I think this is good for security reason as you are likely to share the post password with post link and users who doesn't have a link (most likely anonymous users) to the post can not find the password protected post from search result.

Still if you would like to alter this behavior you can use this snippet from here https://www.isitwp.com/include-password-protected-posts-in-search-results/ just replace `posts_search` filter with [`wpes_posts_search`](https://wpes.secretsofgeeks.com/hooks#wpes_posts_search).

Hope this helps!
