### ISSUE TITLE
Translation related notice after updating to WP 6.7

### ISSUE THREAD

**Issue by leogg** [5um17/wp-extended-search#20]
Function `_load_textdomain_just_in_time` was called incorrectly. Translation loading for the wp-extended-search domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the init action or later.

In `class-wpes-core.php`, changing this line:

`add_action( 'plugins_loaded', array( $this, 'wp_es_plugin_loaded' ) );`

to:

`add_action( 'init', array( $this, 'wp_es_plugin_loaded' ) );`

fixes the issue.

**Comment by 5um17** [comment]
Thanks for the report. 
It has been fixed. Please update to the latest version.
