### ISSUE TITLE
Plugin Settings Menu Add Error for Non Manage-Options users

### ISSUE THREAD

**Issue by verneide** [5um17/wp-extended-search#4]
Just wanted you to know that your recent update to 2.0 caused a bunch of errors to show up on the admin screen for users that do not have "manage_options" in their user role. Something in the constructor file you have that adds the wp-extended search to the menu nav vs in the previous versions you had it showing under the settings menu. I have a few users that only have the ability to view the sites current users and modify them, not allowing them to see settings and other menu items. The recent update was throwing like 6 fatal errors. I had to rollback the plugin to the previous version then all the errors went away.

**Comment by 5um17** [comment]
Thanks for the report. :)

This has been fixed in v2.0.1 please update to the latest version.

**Comment by verneide** [comment]
Perfect. Thank you.

--
Chase Sabers
Digital Operations & Marketing Director
Vern Eide Motorcars
