### ISSUE TITLE
Always using archive template

### ISSUE THREAD

**Issue by jrudenstam** [5um17/wp-extended-search#5]
This is triggering the archive template even on single product query. Am I doing something wrong?

https://github.com/5um17/wp-extended-search/blob/ef1d671cd42b4f42120e77c2ffd0d2313fa56125/includes/integrations/class-wpes-wc.php#L31

**Comment by 5um17** [comment]
Hi,

Thanks for reporting this issue.
Somehow I did not test global setting with product optimization turned on. This has been fixed here https://github.com/5um17/wp-extended-search/commit/954dd158930827451943a0e13ee8ce11db24aec9
Please check if this [works](https://github.com/5um17/wp-extended-search/archive/master.zip) for you?

**Comment by jrudenstam** [comment]
That version works! 👍
